---
Gemfile:
  optional:
    ':acceptance':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
      - gem: beaker-vagrant
      - gem: vagrant-wrapper
.gitignore:
  paths:
    - /update_report.txt
spec/spec_helper.rb:
  spec_overrides: |-
    # Add coverage report.
    RSpec.configure do |c|
      c.after(:suite) do
        RSpec::Puppet::Coverage.report!
      end
    end
.gitlab-ci.yml:
  custom:
    ruby_versions:
      2.5.7:
        tags:
          - docker
      2.4.5:
        tags:
          - docker
    # Due to bugs in the PDK template, the following:
    # beaker:
    #   variables: {}
    #   tags:
    #     - beaker
    # needs to be written like this:
    custom_stages:
      - beaker
    custom_jobs:
      beaker:
        stage: beaker
        variables:
          DOCKER_DRIVER: 'overlay2'
        services:
          - docker:dind
        script:
          - bundle install --with system_tests
          - bundle exec rake beaker
        tags:
          - beaker
