---
Gemfile:
  optional:
    ':acceptance':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
      - gem: beaker-vagrant
      - gem: vagrant-wrapper
      - gem: net-ssh
      - gem: ed25519
      - gem: x25519
      - gem: bcrypt_pbkdf
.gitignore:
  paths:
    - /update_report.txt
.pdkignore:
  paths:
    - /.github/
    - /.ruby-lsp/
    - /.gitlab-ci.yml
    - /.rubocop.yml
    - /.yamllint
spec/spec_helper.rb:
  spec_overrides: |-
    # Add coverage report.
    RSpec.configure do |c|
      c.after(:suite) do
        RSpec::Puppet::Coverage.report!
      end
    end
.travis.yml:
  delete: true
appveyor.yml:
  delete: true
