---
HOSTS:
  centos-9-x64:
    platform: el-9-x86_64
    roles:
      - agent
      - default
    hypervisor: <%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>
    box: generic/centos9s
CONFIG:
  type: aio
  puppet_collection: <%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet8') %>
